apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: desafio-k8s
type: Opaque
stringData:
  POSTGRES_USER: devuser
  POSTGRES_PASSWORD: devpassword123
  POSTGRES_DB: appdb
  PGRST_DB_URI: postgres://devuser:devpassword123@postgres-service:5432/appdb